trigger:
  branches:
    include:
      - main
      - beta

pool:
  name: ubuntu

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      
  - script: echo $(Build.SourceBranchName)
    displayName: 'Print Build.SourceBranchName'
    
  - ${{ if notIn(variables['Build.SourceBranchName'], 'main', 'beta') }}:
      - task: DotNetCoreCLI@2
        displayName: 'Publish for other branches'
        inputs:
          command: 'publish'
          arguments: '/p:Version=$(VersionAlpha).$(Build.BuildId) /p:AssemblyVersion=$(VersionAlpha).$(Build.BuildId) /p:FileVersion=$(VersionAlpha).$(Build.BuildId)'
          publishWebProjects: true

  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      - task: DotNetCoreCLI@2
        displayName: 'Publish for main'
        inputs:
          command: 'publish'
          arguments: '/p:Version=$(VersionAlpha).$(Build.BuildId) /p:AssemblyVersion=$(VersionAlpha).$(Build.BuildId) /p:FileVersion=$(VersionAlpha).$(Build.BuildId)'
          publishWebProjects: true

  - ${{ if eq(variables['Build.SourceBranchName'], 'beta') }}:
      - task: DotNetCoreCLI@2
        displayName: 'Publish for beta'
        inputs:
          command: 'publish'
          arguments: '/p:Version=$(VersionAlpha).$(Build.BuildId) /p:AssemblyVersion=$(VersionAlpha).$(Build.BuildId) /p:FileVersion=$(VersionAlpha).$(Build.BuildId)'
          publishWebProjects: true

  - task: DotNetCoreCLI@2
    displayName: 'test'
    inputs:
      command: 'test'
      projects: '**/*Test.csproj'
      arguments: '--filter "FullyQualifiedName!~IntegrationTest" --collect "XPlat Code Coverage"'

  - task: PublishCodeCoverageResults@2
    displayName: 'Publish coverage test'
    inputs:
      summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

  - task: PublishBuildArtifacts@1
    displayName: 'post artifact'
    inputs:
      PathtoPublish: 'Blueprint/bin/Release/net8.0/publish.zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'