
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        volumes:
            - ./data/zookeeper-data:/var/lib/zookeeper/data
        ports:
            - 22181:2181
    
    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - 29092:29092
        volumes:
            - ./data/kafka-data:/var/lib/kafka/data
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    redis:
        image: redis
        ports:
            - 6379:6379
        volumes:
            - ./data/redis-data:/data

    mongo:
        image: mongo
        ports:
            - 32701:27017
        volumes:
            - ./data/mongo-data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongo
            - MONGO_INITDB_ROOT_PASSWORD=123456

    postgres:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=blueprint
    
    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - 16686:16686
            - 14268:14268
            - 9411:9411
            - 14250:14250
            - 6831:6831/udp
            - 6832:6832/udp
            - 5775:5775/udp
        environment:
            COLLECTOR_ZIPKIN_HTTP_PORT: 9411
            COLLECTOR_GRPC_PORT: 14250
            COLLECTOR_GRPC_TLS_PORT: 14250
            COLLECTOR_HTTP_PORT: 14268
            AGENT_GRPC_PORT: 14250
            AGENT_HTTP_PORT: 14268
            AGENT_REPORTING_HOST_PORT: 14268
            STRATEGY: jaeger
            LOG_LEVEL: debug
        volumes:
            - ./data/jaeger-data:/data


volumes:
    zookeeper-data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./data/zookeeper-data