apiVersion: apps/v1
kind: Deployment
metadata:
  name: blueprint
  namespace: ol-beta
  labels:
    app: blueprint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blueprint
  template:
    metadata:
      labels:
        app: blueprint
    spec:
      securityContext:
        fsGroup: 1001
      volumes:
        - name: configmaps-appsettings-blueprint
          configMap:
            name: configmaps-appsettings-blueprint
            items:
              - key: appsettings.json
                path: appsettings.json
      containers:
        - name: blueprint
          image: asia-southeast2-docker.pkg.dev/nds-oneloan-beta/repo-oneloan-beta/blueprint:beta
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/configurations/
              name: configmaps-appsettings-blueprint
          env:
            - name: TZ
              value: Asia/Jakarta
          ports:
            - name: blueprint
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.2
          env:
            - name: TZ
              value: Asia/Jakarta
            - name: INSTANCE_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: configmaps-sqlproxy-ol-beta
                  key: connectionname  
          args:
            - "--private-ip"
            - "--port=5432"
            - "$(INSTANCE_CONNECTION)"
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 10m
              memory: 15Mi
            requests:
              cpu: 10m
              memory: 15Mi 
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blueprint
  namespace: ol-beta
spec:
  scaleTargetRef:
    kind: Deployment
    name: blueprint
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "backendconfig-ol-blueprint"}'
  name: blueprint-service
  labels:
    app: blueprint
  namespace: ol-beta
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: blueprint
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  namespace: ol-beta
  name: backendconfig-ol-blueprint
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /blueprint/healthchecks
    port: 8080
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: prom-blueprint
  namespace: ol-beta
  labels:
    app: blueprint
spec:
  selector:
    matchLabels:
      app: blueprint
  endpoints:
   - port: blueprint
     interval: 15s